import { 
  Councilor, 
  Session, 
  Deliberation, 
  Budget, 
  BudgetLine,
  Employee,
  Asset,
  InvestmentProject,
  PublicContract,
  ComplianceAlert,
  TutelleTransmission,
  DashboardStats
} from '@/types';

// Mock Councilors for Mpassa department
export const mockCouncilors: Councilor[] = [
  {
    id: 'c1',
    tenantId: 'mpassa',
    firstName: 'Jean-Baptiste',
    lastName: 'NTOUTOUME',
    gender: 'M',
    dateOfBirth: new Date('1965-03-15'),
    placeOfBirth: 'Franceville',
    profession: 'Administrateur Civil',
    email: 'jb.ntoutoume@conseil-mpassa.ga',
    phone: '+241 77 00 00 01',
    address: 'Franceville, Haut-Ogooué',
    photo: '/placeholder.svg',
    function: 'president',
    electionDate: new Date('2023-11-15'),
    mandateStart: new Date('2023-12-01'),
    mandateEnd: new Date('2028-11-30'),
    status: 'active',
    biography: 'Ancien préfet, élu président du Conseil Départemental de Mpassa en 2023.',
    createdAt: new Date('2023-12-01'),
  },
  {
    id: 'c2',
    tenantId: 'mpassa',
    firstName: 'Marie-Claire',
    lastName: 'OBIANG',
    gender: 'F',
    dateOfBirth: new Date('1972-07-22'),
    placeOfBirth: 'Moanda',
    profession: 'Enseignante',
    email: 'mc.obiang@conseil-mpassa.ga',
    phone: '+241 77 00 00 02',
    address: 'Moanda, Haut-Ogooué',
    function: 'vice_president',
    electionDate: new Date('2023-11-15'),
    mandateStart: new Date('2023-12-01'),
    mandateEnd: new Date('2028-11-30'),
    status: 'active',
    createdAt: new Date('2023-12-01'),
  },
  {
    id: 'c3',
    tenantId: 'mpassa',
    firstName: 'Pierre',
    lastName: 'MOUSSAVOU',
    gender: 'M',
    dateOfBirth: new Date('1968-11-08'),
    placeOfBirth: 'Franceville',
    profession: 'Ingénieur des Mines',
    email: 'p.moussavou@conseil-mpassa.ga',
    phone: '+241 77 00 00 03',
    address: 'Franceville, Haut-Ogooué',
    function: 'councilor',
    commission: 'Budget et Finances',
    electionDate: new Date('2023-11-15'),
    mandateStart: new Date('2023-12-01'),
    mandateEnd: new Date('2028-11-30'),
    status: 'active',
    createdAt: new Date('2023-12-01'),
  },
  {
    id: 'c4',
    tenantId: 'mpassa',
    firstName: 'Sylvie',
    lastName: 'NDONG',
    gender: 'F',
    dateOfBirth: new Date('1980-04-18'),
    placeOfBirth: 'Libreville',
    profession: 'Juriste',
    email: 's.ndong@conseil-mpassa.ga',
    phone: '+241 77 00 00 04',
    address: 'Franceville, Haut-Ogooué',
    function: 'councilor',
    commission: 'Affaires Juridiques',
    electionDate: new Date('2023-11-15'),
    mandateStart: new Date('2023-12-01'),
    mandateEnd: new Date('2028-11-30'),
    status: 'active',
    createdAt: new Date('2023-12-01'),
  },
];

// Mock Sessions
export const mockSessions: Session[] = [
  {
    id: 's1',
    tenantId: 'mpassa',
    type: 'ordinary',
    quarter: 'T4',
    year: 2025,
    title: 'Session Ordinaire T4 2025 - Budget Primitif 2026',
    convocationDate: new Date('2025-10-28'),
    startDate: new Date('2025-11-12'),
    endDate: new Date('2025-11-15'),
    location: 'Salle du Conseil, Hôtel du Département',
    agenda: [
      {
        id: 'a1',
        order: 1,
        title: 'Approbation du PV de la session précédente',
        description: 'Lecture et approbation du procès-verbal de la session T2 2025',
        type: 'vote',
        documents: [],
      },
      {
        id: 'a2',
        order: 2,
        title: 'Vote du Budget Primitif 2026',
        description: 'Examen et vote du budget primitif pour l\'exercice 2026',
        type: 'deliberation',
        documents: [],
      },
      {
        id: 'a3',
        order: 3,
        title: 'Programme d\'investissement 2026',
        description: 'Présentation et adoption du programme d\'investissement',
        type: 'deliberation',
        documents: [],
      },
    ],
    status: 'completed',
    quorumRequired: 8,
    quorumMet: true,
    attendees: [],
    createdAt: new Date('2025-10-01'),
  },
  {
    id: 's2',
    tenantId: 'mpassa',
    type: 'ordinary',
    quarter: 'T2',
    year: 2026,
    title: 'Session Ordinaire T2 2026 - Compte Administratif 2025',
    convocationDate: new Date('2026-04-15'),
    startDate: new Date('2026-05-02'),
    location: 'Salle du Conseil, Hôtel du Département',
    agenda: [],
    status: 'planned',
    quorumRequired: 8,
    quorumMet: false,
    attendees: [],
    createdAt: new Date('2026-01-10'),
  },
];

// Mock Deliberations
export const mockDeliberations: Deliberation[] = [
  {
    id: 'd1',
    tenantId: 'mpassa',
    sessionId: 's1',
    number: '2025/CD-MPA/024',
    year: 2025,
    date: new Date('2025-11-13'),
    subject: 'Adoption du Budget Primitif 2026',
    content: 'Le Conseil Départemental de Mpassa, réuni en session ordinaire...',
    type: 'budgetary',
    vote: {
      id: 'v1',
      deliberationId: 'd1',
      type: 'public',
      forVotes: 10,
      againstVotes: 1,
      abstentions: 1,
      proxies: 0,
      quorumMet: true,
      result: 'adopted',
      conductedAt: new Date('2025-11-13'),
      auditTrail: [],
    },
    status: 'approved',
    signedBy: 'Jean-Baptiste NTOUTOUME',
    signedAt: new Date('2025-11-15'),
    transmittedAt: new Date('2025-11-18'),
    receiptNumber: 'RT-2025-MPA-048',
    tutelleStatus: 'approved',
    executoryDate: new Date('2025-12-03'),
    documents: [],
    createdAt: new Date('2025-11-13'),
  },
  {
    id: 'd2',
    tenantId: 'mpassa',
    sessionId: 's1',
    number: '2025/CD-MPA/025',
    year: 2025,
    date: new Date('2025-11-14'),
    subject: 'Adoption du Programme d\'Investissement 2026',
    content: 'Le Conseil Départemental de Mpassa, après examen...',
    type: 'budgetary',
    vote: {
      id: 'v2',
      deliberationId: 'd2',
      type: 'public',
      forVotes: 11,
      againstVotes: 0,
      abstentions: 1,
      proxies: 0,
      quorumMet: true,
      result: 'adopted',
      conductedAt: new Date('2025-11-14'),
      auditTrail: [],
    },
    status: 'transmitted',
    signedBy: 'Jean-Baptiste NTOUTOUME',
    signedAt: new Date('2025-11-15'),
    transmittedAt: new Date('2025-11-18'),
    receiptNumber: 'RT-2025-MPA-049',
    tutelleStatus: 'pending',
    documents: [],
    createdAt: new Date('2025-11-14'),
  },
];

// Mock Budget Lines
export const mockBudgetLines: BudgetLine[] = [
  // Operating Revenues
  { id: 'bl1', code: '70', title: 'Produits des services', chapter: '70', article: '70', section: 'operating', type: 'revenue', forecastAmount: 85000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 68500000, available: 16500000, executionRate: 80.6 },
  { id: 'bl2', code: '73', title: 'Impôts et taxes', chapter: '73', article: '73', section: 'operating', type: 'revenue', forecastAmount: 145000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 122000000, available: 23000000, executionRate: 84.1 },
  { id: 'bl3', code: '74', title: 'Dotations et participations', chapter: '74', article: '74', section: 'operating', type: 'revenue', forecastAmount: 180000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 180000000, available: 0, executionRate: 100 },
  { id: 'bl4', code: '75', title: 'Autres produits de gestion courante', chapter: '75', article: '75', section: 'operating', type: 'revenue', forecastAmount: 25000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 18500000, available: 6500000, executionRate: 74 },
  
  // Operating Expenditures
  { id: 'bl5', code: '60', title: 'Achats et variation stocks', chapter: '60', article: '60', section: 'operating', type: 'expenditure', forecastAmount: 45000000, engagedAmount: 42000000, liquidatedAmount: 38000000, paidAmount: 35000000, available: 3000000, executionRate: 77.8 },
  { id: 'bl6', code: '61', title: 'Services extérieurs', chapter: '61', article: '61', section: 'operating', type: 'expenditure', forecastAmount: 35000000, engagedAmount: 32000000, liquidatedAmount: 28000000, paidAmount: 25000000, available: 3000000, executionRate: 71.4 },
  { id: 'bl7', code: '62', title: 'Autres services extérieurs', chapter: '62', article: '62', section: 'operating', type: 'expenditure', forecastAmount: 28000000, engagedAmount: 25000000, liquidatedAmount: 22000000, paidAmount: 20000000, available: 3000000, executionRate: 71.4 },
  { id: 'bl8', code: '64', title: 'Charges de personnel', chapter: '64', article: '64', section: 'operating', type: 'expenditure', forecastAmount: 185000000, engagedAmount: 185000000, liquidatedAmount: 170000000, paidAmount: 165000000, available: 0, executionRate: 89.2 },
  { id: 'bl9', code: '65', title: 'Autres charges de gestion courante', chapter: '65', article: '65', section: 'operating', type: 'expenditure', forecastAmount: 22000000, engagedAmount: 18000000, liquidatedAmount: 15000000, paidAmount: 12000000, available: 4000000, executionRate: 54.5 },
  { id: 'bl10', code: '67', title: 'Charges exceptionnelles', chapter: '67', article: '67', section: 'operating', type: 'expenditure', forecastAmount: 8000000, engagedAmount: 5000000, liquidatedAmount: 4000000, paidAmount: 3500000, available: 3000000, executionRate: 43.8 },
  
  // Investment Revenues
  { id: 'bl11', code: '10', title: 'Dotations et fonds divers', chapter: '10', article: '10', section: 'investment', type: 'revenue', forecastAmount: 120000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 95000000, available: 25000000, executionRate: 79.2 },
  { id: 'bl12', code: '13', title: 'Subventions d\'investissement', chapter: '13', article: '13', section: 'investment', type: 'revenue', forecastAmount: 85000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 45000000, available: 40000000, executionRate: 52.9 },
  { id: 'bl13', code: '16', title: 'Emprunts et dettes assimilées', chapter: '16', article: '16', section: 'investment', type: 'revenue', forecastAmount: 50000000, engagedAmount: 0, liquidatedAmount: 0, paidAmount: 50000000, available: 0, executionRate: 100 },
  
  // Investment Expenditures
  { id: 'bl14', code: '20', title: 'Immobilisations incorporelles', chapter: '20', article: '20', section: 'investment', type: 'expenditure', forecastAmount: 15000000, engagedAmount: 12000000, liquidatedAmount: 10000000, paidAmount: 8500000, available: 3000000, executionRate: 56.7 },
  { id: 'bl15', code: '21', title: 'Immobilisations corporelles', chapter: '21', article: '21', section: 'investment', type: 'expenditure', forecastAmount: 180000000, engagedAmount: 165000000, liquidatedAmount: 120000000, paidAmount: 95000000, available: 15000000, executionRate: 52.8 },
  { id: 'bl16', code: '23', title: 'Immobilisations en cours', chapter: '23', article: '23', section: 'investment', type: 'expenditure', forecastAmount: 45000000, engagedAmount: 42000000, liquidatedAmount: 35000000, paidAmount: 28000000, available: 3000000, executionRate: 62.2 },
  { id: 'bl17', code: '16', title: 'Remboursement emprunts', chapter: '16', article: '16', section: 'investment', type: 'expenditure', forecastAmount: 15000000, engagedAmount: 15000000, liquidatedAmount: 15000000, paidAmount: 12500000, available: 0, executionRate: 83.3 },
];

// Mock Employees
export const mockEmployees: Employee[] = [
  {
    id: 'e1',
    tenantId: 'mpassa',
    matricule: 'SG-MPA-001',
    type: 'seconded',
    firstName: 'Alain',
    lastName: 'MBOUMBA',
    gender: 'M',
    dateOfBirth: new Date('1970-05-12'),
    placeOfBirth: 'Libreville',
    nationality: 'Gabonaise',
    idNumber: '0001234567',
    idType: 'cni',
    address: 'Franceville, Haut-Ogooué',
    phone: '+241 77 00 00 10',
    email: 'sg@conseil-mpassa.ga',
    maritalStatus: 'married',
    numberOfChildren: 4,
    recruitmentDate: new Date('2024-01-15'),
    grade: 'Administrateur Civil Principal',
    echelon: 8,
    index: 1200,
    position: 'Secrétaire Général',
    service: 'Direction Générale',
    baseSalary: 1500000,
    status: 'active',
    createdAt: new Date('2024-01-15'),
    documents: [],
  },
  {
    id: 'e2',
    tenantId: 'mpassa',
    matricule: 'DAF-MPA-001',
    type: 'seconded',
    firstName: 'Cécile',
    lastName: 'NGUEMA',
    gender: 'F',
    dateOfBirth: new Date('1975-09-28'),
    placeOfBirth: 'Port-Gentil',
    nationality: 'Gabonaise',
    idNumber: '0002345678',
    idType: 'cni',
    address: 'Franceville, Haut-Ogooué',
    phone: '+241 77 00 00 11',
    email: 'daf@conseil-mpassa.ga',
    maritalStatus: 'married',
    numberOfChildren: 2,
    recruitmentDate: new Date('2024-02-01'),
    grade: 'Inspecteur des Finances',
    echelon: 6,
    index: 950,
    position: 'Directeur des Affaires Financières',
    service: 'Direction des Affaires Financières',
    baseSalary: 1200000,
    status: 'active',
    createdAt: new Date('2024-02-01'),
    documents: [],
  },
];

// Mock Assets
export const mockAssets: Asset[] = [
  {
    id: 'a1',
    tenantId: 'mpassa',
    inventoryNumber: 'IMM-MPA-001',
    category: 'public_domain',
    type: 'building',
    nature: 'Bâtiment administratif',
    designation: 'Hôtel du Département de Mpassa',
    description: 'Siège du Conseil Départemental',
    address: 'Avenue de l\'Indépendance, Franceville',
    commune: 'Franceville',
    area: 2500,
    latitude: -1.6333,
    longitude: 13.5833,
    acquisitionDate: new Date('1985-01-01'),
    acquisitionMode: 'construction',
    originalValue: 850000000,
    currentValue: 1200000000,
    lastValuationDate: new Date('2024-06-15'),
    condition: 'good',
    assignment: 'Services administratifs',
    occupancyMode: 'public_service',
    insured: true,
    insuranceCompany: 'NSIA Assurances',
    insuranceNumber: 'POL-2024-00125',
    insuranceExpiry: new Date('2025-12-31'),
    photos: [],
    documents: [],
    maintenanceHistory: [],
    status: 'active',
    createdAt: new Date('2020-01-01'),
  },
  {
    id: 'a2',
    tenantId: 'mpassa',
    inventoryNumber: 'VEH-MPA-001',
    category: 'private_domain',
    type: 'vehicle',
    nature: 'Véhicule de fonction',
    designation: 'Toyota Land Cruiser Prado - Président',
    description: 'Véhicule de fonction du Président du Conseil Départemental',
    acquisitionDate: new Date('2024-03-15'),
    acquisitionMode: 'purchase',
    originalValue: 45000000,
    currentValue: 42000000,
    lastValuationDate: new Date('2024-12-01'),
    condition: 'excellent',
    assignment: 'Présidence',
    insured: true,
    insuranceCompany: 'OGAR',
    insuranceNumber: 'AUTO-2024-00089',
    insuranceExpiry: new Date('2025-03-14'),
    photos: [],
    documents: [],
    maintenanceHistory: [],
    status: 'active',
    createdAt: new Date('2024-03-15'),
  },
];

// Mock Investment Projects
export const mockProjects: InvestmentProject[] = [
  {
    id: 'p1',
    tenantId: 'mpassa',
    code: 'P-2025-001',
    title: 'Construction du Centre de Santé de Lékori',
    description: 'Construction d\'un centre de santé de niveau 2 avec maternité',
    category: 'building',
    projectType: 'construction',
    objectives: 'Améliorer l\'accès aux soins de santé pour 15 000 habitants',
    beneficiaries: 'Population de Lékori et villages environnants',
    location: 'Lékori, Département de Mpassa',
    inscriptionYear: 2025,
    deliberationNumber: '2024/CD-MPA/018',
    priority: 1,
    estimatedCost: 220000000,
    actualCost: 205000000,
    funding: [
      { source: 'state_grant', amount: 150000000, percentage: 68 },
      { source: 'own_funds', amount: 50000000, percentage: 23 },
      { source: 'fdl', amount: 20000000, percentage: 9 },
    ],
    plannedStartDate: new Date('2025-03-01'),
    plannedEndDate: new Date('2026-02-28'),
    actualStartDate: new Date('2025-03-15'),
    durationMonths: 12,
    contractNumber: 'MC-2025-001',
    contractor: 'SOBATI GABON',
    contractAmount: 195000000,
    progressPercentage: 65,
    phase: 'execution',
    status: 'in_progress',
    photos: [],
    documents: [],
    createdAt: new Date('2024-11-20'),
  },
  {
    id: 'p2',
    tenantId: 'mpassa',
    code: 'P-2025-002',
    title: 'Réhabilitation de la Route Départementale RD5',
    description: 'Réhabilitation et bitumage de 15km de route',
    category: 'infrastructure',
    projectType: 'rehabilitation',
    objectives: 'Désenclaver les villages de la zone nord',
    beneficiaries: 'Population rurale (environ 8 000 habitants)',
    location: 'Axe Franceville - Bongoville',
    inscriptionYear: 2025,
    deliberationNumber: '2024/CD-MPA/019',
    priority: 2,
    estimatedCost: 180000000,
    funding: [
      { source: 'state_grant', amount: 120000000, percentage: 67 },
      { source: 'own_funds', amount: 60000000, percentage: 33 },
    ],
    plannedStartDate: new Date('2025-06-01'),
    plannedEndDate: new Date('2026-05-31'),
    durationMonths: 12,
    progressPercentage: 0,
    phase: 'tender',
    status: 'planned',
    photos: [],
    documents: [],
    createdAt: new Date('2024-11-20'),
  },
];

// Mock Compliance Alerts
export const mockAlerts: ComplianceAlert[] = [
  {
    id: 'alert1',
    tenantId: 'mpassa',
    level: 'warning',
    category: 'budget',
    title: 'Charges de personnel élevées',
    message: 'Les charges de personnel représentent 62% du budget de fonctionnement (seuil recommandé: 60%)',
    action: 'Réviser la politique de recrutement',
    acknowledged: false,
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'alert2',
    tenantId: 'mpassa',
    level: 'info',
    category: 'session',
    title: 'Session T2 2026 à programmer',
    message: 'La session ordinaire du 2ème trimestre doit être convoquée avant le 15 avril 2026',
    action: 'Planifier la session conseil',
    deadline: new Date('2026-04-15'),
    acknowledged: false,
    createdAt: new Date('2026-01-05'),
  },
  {
    id: 'alert3',
    tenantId: 'mpassa',
    level: 'alert',
    category: 'transmission',
    title: 'Délibération en attente d\'approbation',
    message: 'La délibération n°2025/CD-MPA/025 est en attente d\'approbation depuis 12 jours',
    acknowledged: false,
    createdAt: new Date('2025-11-30'),
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  budget: {
    voted: 520000000,
    executed: 389000000,
    executionRate: 74.8,
    operatingBalance: 45000000,
    investmentBalance: 28000000,
  },
  sessions: {
    held: 2,
    required: 2,
    nextSession: new Date('2026-05-02'),
  },
  deliberations: {
    total: 25,
    transmitted: 24,
    approved: 22,
    pending: 2,
  },
  personnel: {
    total: 225,
    elected: 12,
    agents: 213,
    payrollCost: 165000000,
  },
  projects: {
    total: 8,
    inProgress: 5,
    completed: 2,
    delayed: 1,
  },
  compliance: {
    score: 87,
    alerts: 3,
    criticalAlerts: 0,
  },
};

// Calculate budget summary
export const calculateBudgetSummary = (lines: BudgetLine[]) => {
  const operatingRevenues = lines.filter(l => l.section === 'operating' && l.type === 'revenue');
  const operatingExpenditures = lines.filter(l => l.section === 'operating' && l.type === 'expenditure');
  const investmentRevenues = lines.filter(l => l.section === 'investment' && l.type === 'revenue');
  const investmentExpenditures = lines.filter(l => l.section === 'investment' && l.type === 'expenditure');

  const sum = (arr: BudgetLine[], key: keyof BudgetLine) => 
    arr.reduce((acc, l) => acc + (l[key] as number), 0);

  return {
    operating: {
      forecastRevenue: sum(operatingRevenues, 'forecastAmount'),
      forecastExpenditure: sum(operatingExpenditures, 'forecastAmount'),
      paidRevenue: sum(operatingRevenues, 'paidAmount'),
      paidExpenditure: sum(operatingExpenditures, 'paidAmount'),
      revenueRate: (sum(operatingRevenues, 'paidAmount') / sum(operatingRevenues, 'forecastAmount') * 100).toFixed(1),
      expenditureRate: (sum(operatingExpenditures, 'paidAmount') / sum(operatingExpenditures, 'forecastAmount') * 100).toFixed(1),
    },
    investment: {
      forecastRevenue: sum(investmentRevenues, 'forecastAmount'),
      forecastExpenditure: sum(investmentExpenditures, 'forecastAmount'),
      paidRevenue: sum(investmentRevenues, 'paidAmount'),
      paidExpenditure: sum(investmentExpenditures, 'paidAmount'),
      revenueRate: (sum(investmentRevenues, 'paidAmount') / sum(investmentRevenues, 'forecastAmount') * 100).toFixed(1),
      expenditureRate: (sum(investmentExpenditures, 'paidAmount') / sum(investmentExpenditures, 'forecastAmount') * 100).toFixed(1),
    },
  };
};
